### ISSUE TITLE
Avoid duplicate commenting.

### ISSUE THREAD

**Issue by bboe** [appfolio/farcy#1]
Force pushes to the branches associated with a pull request currently results in duplicate comments. farcy should avoid making comments it has already made.

**Comment by balloob** [comment]
I've started some work on this in 998dd31e66e06f9db2a00642ac7905e94c2fc7ce. Right now I only added methods to identify comments on the PR made by Farcy.

I can see different approaches when a force push comes in:

1. Blast all old comments away and let the normal logic run.
2. Add a message to all old comments that this comment has been invalidated by a force push
3. Sync new comments to the old comments:
  - Remove comments for lines that no longer have comments/Mark them as outdated
  - Update old comments with new errors
  - Add comments for new lines with comments

**Comment by bboe** [comment]
Maybe for simplicity doing 1 might be best.

**Comment by balloob** [comment]
Implemented approach 1 [here](https://github.com/balloob/farcy/tree/handle-force-push) but only figured out in the end that the `forced` attribute is only there when the PushEvent is received as a webhook.

**Comment by bboe** [comment]
As pointed out in the chat, we probably should sync comments to avoid unnecessary email spam. If we cannot reliably do that, perhaps we should hook farcy up to a simple web service for the purpose of displaying results.

**Comment by balloob** [comment]
[This method](https://github.com/appfolio/farcy/commit/998dd31e66e06f9db2a00642ac7905e94c2fc7ce#diff-3e29103a64ca81c056341189d2ffa4c7R382) will return the Farcy review comments per line no. Syncing them should be straight forward.

**Comment by bboe** [comment]
Though line numbers change with subsequent modifications so it may be a bit more difficult. Maybe we can ignore that case though initially.

**Comment by balloob** [comment]
Fixed in PR #23
