### ISSUE TITLE
Support linter configuration files

### ISSUE THREAD

**Issue by balloob** [appfolio/farcy#21]
Rubocop allows specifying a rubocop.yml to enable / disable / configure individual linter checks. So does jshint (which I plan to add support for) 

To do this, we would probably have to clone the repo locally, run linter on all the code and filter the results by changed files / lines.

**Comment by bboe** [comment]
I was thinking that the rubocop handler could dynamically pull the rubocop file out of the root of the repository if it exists, and default to some low-impact yml file otherwise (trailing whitespace, tabs, and end of file whitespace).

Although, I suppose since farcy currently requires a 1 to 1 mapping between process and repo, maybe that's unnecessary and possibly unsafe to dynamically execute _untrusted_ yml files.

**Comment by balloob** [comment]
I like the cloning of the repo and checking out the branch of the PR:

Biggest plus is that it will open up a path to use more extensive linters like [PyLint](http://www.pylint.org). Once pylint support is there I am planning to start using Farcy for my side project [Home Assistant](https://github.com/balloob/home-assistant).

It will also make it trivial for Rubocop to find the configuration files. I don't know if many repos do it but Rubocop allows configuration files in any parent folder. From the [Rubocop readme](https://github.com/bbatsov/rubocop#configuration):
> RuboCop will start looking for the configuration file in the directory where the inspected file is and continue its way up to the root directory.

About untrusted YML files, wouldn't this be a responsibility of the user as the user is pointing this at their own repo?

**Comment by bboe** [comment]
Yes, checkouts make sense in the context you described.

> About untrusted YML files, wouldn't this be a responsibility of the user as the user is pointing this at their own repo?

In that context that you have full control over who accesses your repository, yes. However, for an open source project, I wouldn't enable rubocop as all pull requests (untrusted) would be tested.

**Comment by balloob** [comment]
Fixed in PR #26
