### ISSUE TITLE
Rubocop complains about temporary filename not being snake_case

### ISSUE THREAD

**Issue by balloob** [appfolio/farcy#32]
Using default configuration the Rubocop handler will complain for each Ruby file about the filename not being snake_cased due to us storing the file in a temporary file with a different name.

We should configure Rubocop to disable this cop by default.

**Comment by bboe** [comment]
Could we also just save the temporary file with the same name?

**Comment by balloob** [comment]
Yes, we could use [`tempfile.gettempdir`](https://docs.python.org/2/library/tempfile.html#tempfile.gettempdir) instead of `tempfile. NamedTemporaryFile`. We probably want to create a subdirectory to ensure that we don't conflict with other programs using the temp folder. We also would want the subdirectory name to contain something unique to that running Farcy instance (eg `id(self)`) so that a user can have multiple processes running simultaneously.

**Comment by bboe** [comment]
`tempfile.mkdtemp` would make a random temporary sub directory in which to download named files to. Then we need only ensure that directory is cleaned up with a finally clause when all is said and done.

**Comment by balloob** [comment]
Current work around for this problem is to disable the snake case cop in your handler config.

**Comment by bboe** [comment]
I'm going to try to pick this up later today.

**Comment by bboe** [comment]
rubocop can now compare on the actual filename. Hopefully it won't complain about it's containing directory name :).
