### ISSUE TITLE
Farcy expects uniform outputs for check_output([self.BINARY, '--version']

### ISSUE THREAD

**Issue by danrozenberg** [appfolio/farcy#76]
I am planing on adding yardstick to farcy, so we can enforce certain documentation rules in Ruby.

Farcy expects ``check_output([self.BINARY, '--version']`` to return the version and nothing else. Sometimes, though, that is not the case; yardstick returns its name followed by it's version number.

The following [PR](https://github.com/appfolio/farcy/pull/75) is good enough to allow yardstick to work correctly.

However, another solution would be to optionally specify a handler regex that reads the --version output correctly.

**Comment by balloob** [comment]
You can implement `version_callback` on your handler to process the version string. By default it strips the output, but for example [ESLint](https://github.com/appfolio/farcy/blob/master/farcy/handlers.py#L170-L172) removes the starting `v`.

**Comment by danrozenberg** [comment]
Aha!
Thanks, @balloob
